package application;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.effect.Bloom;
import javafx.scene.effect.DropShadow;
import javafx.scene.effect.Reflection;
import javafx.scene.image.Image;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundImage;
import javafx.scene.layout.BackgroundPosition;
import javafx.scene.layout.BackgroundRepeat;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class Start extends Application {
	
	private Stage stage;
	private Scene startScene;
	private Pane startPane;
	private Label spaceMessage = new Label("Press space to begin");
	private Label title = new Label("Space Invaders!");
	private Group group;
	private SpaceInvaders spaceInvadersGame;
	
	/**
	 * Return a key event handler that moves to the rectangle to the left or the
	 * right depending on what key event is generated by the associated node.
	 * 
	 * @return the key event handler
	 */
	public EventHandler<KeyEvent> createKeyHandler() {
		return event -> {
			switch (event.getCode()) {
			case LEFT: // KeyCode.LEFT
				break;
			default:
				break;
			} // switch

		};
	} // createKeyHandler

	/** {@inheritDoc} */
	public void start(Stage s) {
		
		group = new Group();
		stage = s;
		startPane = new Pane();
		Image background = new Image("Space_Invaders_Background.jpg", 640, 480, false, true);
		BackgroundImage bgImage = new BackgroundImage(background, BackgroundRepeat.REPEAT, BackgroundRepeat.REPEAT,
				BackgroundPosition.DEFAULT, null);
		startPane.setBackground(new Background(bgImage));
		
		//title
		title.setFont(new Font("Impact", 42));
		title.setTextFill(Color.WHITE);
		title.setLayoutX(180);
		title.setLayoutY(100);
		title.setCache(true);
		Bloom bloom = new Bloom();
		title.setEffect(bloom);
		
		//Command
		spaceMessage.setFont(new Font("Impact", 28));
		spaceMessage.setTextFill(Color.WHITE);
		spaceMessage.setLayoutX(195);
		spaceMessage.setLayoutY(350);
		
		//text effect
		DropShadow ds = new DropShadow();
		ds.setOffsetY(5.0);
		ds.setOffsetX(5.0);
		ds.setColor(Color.GRAY);
		Reflection reflection = new Reflection();
		ds.setInput(reflection);
		spaceMessage.setEffect(ds);
		
		group.getChildren().addAll(title, spaceMessage);
	    startPane.getChildren().add(group);
	    group.requestFocus();
	 
		startScene = new Scene(startPane, 640, 480);
		stage.setTitle("Space Invaders!");
		stage.setScene(startScene);
		stage.sizeToScene();
		stage.setResizable(false);
		stage.show();
		
		 startScene.setOnKeyPressed(new EventHandler<KeyEvent>() {
		    	@Override
		    	public void handle (KeyEvent event) {
		    		switch (event.getCode()) {
		    		case SPACE: // KeyCode.SPACE
		    			spaceInvadersGame= new SpaceInvaders(stage);
		    			stage.setScene(spaceInvadersGame.getScene());
	            	default:
		    		}
		    	}
		    });
	} // start
	
	public Stage setStage(Stage s) {
		return s = this.stage;
	}
}
